### ISSUE TITLE
Only update environments/modules by filter

### ISSUE THREAD

**Issue by arska** [vshn/crmngr#10]
When updating one module in one environment (with -e and -m respectively) crmngr still updates all the modules from all environments taking a long time.

**Comment by tobru** [comment]
You mean the caching mechanism I guess? When first run (per day), crmngr updates the local cache which takes a long time. 
When using -m it probably could make sense to just update the cache for the selected module and when using -e just the cache for the modules in the selected environment. What do you think @andrekeller?

**Comment by andrekeller** [comment]
This has been changed and will be in the 2.0.0rc1 release, to be released today.
