### ISSUE TITLE
Omit --git when updating a module

### ISSUE THREAD

**Issue by tobru** [vshn/crmngr#7]
Would be nice if the `--git` parameter could be skipped when updating a tag of a module. F.e. just enter `crmngr update -e MyEnvironment -m mymodule --tag v1.4.2`. If `-e` matches multiple environments, it should fail with an error message, saying that this only works on one environment.

**Comment by tobru** [comment]
As discussed: `--git` could be kept, but without the git URL. So to update the example from above: `crmngr update -e MyEnvironment -m mymodule --git --tag v1.4.2`

**Comment by andrekeller** [comment]
This has been changed and will be in the 2.0.0rc1 release, to be released today.
