### ISSUE TITLE
Stop on git error

### ISSUE THREAD

**Issue by andrewfraley** [vshn/crmngr#8]
I was struggling to figure out why crmngr exited cleanly when using the update command, yet nothing was committed or pushed.  It would probably be best to exit if git exit status != 0 and spit out the git client error if possible.  

For me it was exit code 128, in which case you just need to run:

```
git config --global user.email "you@example.com"
git config --global user.name "Your Name"
```

Great project btw, I've been casually searching for something like this for months and was about to roll my own.   Thanks!

**Comment by andrekeller** [comment]
@andrewfraley, thank you for the feedback. I will have a look at this on Friday.

**Comment by andrekeller** [comment]
This has been changed and will be in the 2.0.0rc1 release, to be released today.
