### ISSUE TITLE
Add newline between each module

### ISSUE THREAD

**Issue by andrewfraley** [vshn/crmngr#9]
I'm not sure how others would feel about it, but the Puppetfile is a lot more readable with an extra newline between each module.  If not by default, maybe an option that could be placed in the profiles file.

**Comment by andrekeller** [comment]
hi,

this might make sense for modules that span more than one line. I'm a bit reluctant to add that as a default option though.

**Comment by andrekeller** [comment]
I currently do not see a compelling reason for this, and it just add additional overhead to the parsing.
